#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 22, 2020 03:44:43 AM PST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import sm_train_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    sm_train_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    sm_train_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family Arial -size 10 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font9 = "-family Arial -size 12 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("572x655+718+137")
        top.minsize(176, 1)
        top.maxsize(1924, 1050)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")

        self.Label1 = tk.Label(self.Canvas1)
        self.Label1.place(relx=0.245, rely=0.031, height=35, width=303)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Training Hyperparameters''')

        self.Label2 = tk.Label(self.Canvas1)
        self.Label2.place(relx=0.087, rely=0.137, height=31, width=49)
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''n_job''')

        self.Label3 = tk.Label(self.Canvas1)
        self.Label3.place(relx=0.087, rely=0.198, height=31, width=133)
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''shared_memory''')

        self.Label4 = tk.Label(self.Canvas1)
        self.Label4.place(relx=0.087, rely=0.26, height=31, width=126)
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''train_rough_len''')

        self.Label5 = tk.Label(self.Canvas1)
        self.Label5.place(relx=0.087, rely=0.382, height=31, width=165)
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''train_rough_radiusin''')

        self.Label6 = tk.Label(self.Canvas1)
        self.Label6.place(relx=0.087, rely=0.443, height=31, width=171)
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''train_rough_radiusfin''')

        self.Label7 = tk.Label(self.Canvas1)
        self.Label7.place(relx=0.087, rely=0.565, height=31, width=142)
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''train_finetune_len''')

        self.Entry1 = tk.Entry(self.Canvas1)
        self.Entry1.place(relx=0.437, rely=0.137,height=26, relwidth=0.427)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Entry2 = tk.Entry(self.Canvas1)
        self.Entry2.place(relx=0.437, rely=0.198,height=26, relwidth=0.427)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Entry3 = tk.Entry(self.Canvas1)
        self.Entry3.place(relx=0.437, rely=0.26,height=26, relwidth=0.427)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")

        self.Entry4 = tk.Entry(self.Canvas1)
        self.Entry4.place(relx=0.437, rely=0.382,height=26, relwidth=0.427)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")

        self.Entry5 = tk.Entry(self.Canvas1)
        self.Entry5.place(relx=0.437, rely=0.443,height=26, relwidth=0.427)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")

        self.Entry6 = tk.Entry(self.Canvas1)
        self.Entry6.place(relx=0.437, rely=0.565,height=26, relwidth=0.427)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")

        self.Label8 = tk.Label(self.Canvas1)
        self.Label8.place(relx=0.087, rely=0.626, height=31, width=181)
        self.Label8.configure(anchor='w')
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''train_finetune_radiusin''')

        self.Entry7 = tk.Entry(self.Canvas1)
        self.Entry7.place(relx=0.437, rely=0.626,height=26, relwidth=0.427)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(insertbackground="black")

        self.Label9 = tk.Label(self.Canvas1)
        self.Label9.place(relx=0.087, rely=0.702, height=31, width=187)
        self.Label9.configure(anchor='w')
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''train_finetune_radiusfin''')

        self.Entry8 = tk.Entry(self.Canvas1)
        self.Entry8.place(relx=0.437, rely=0.702,height=26, relwidth=0.427)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(insertbackground="black")

        self.Label10 = tk.Label(self.Canvas1)
        self.Label10.place(relx=0.087, rely=0.763, height=31, width=124)
        self.Label10.configure(anchor='w')
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''train_len_factor''')

        self.Entry9 = tk.Entry(self.Canvas1)
        self.Entry9.place(relx=0.437, rely=0.763,height=26, relwidth=0.427)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(insertbackground="black")

        self.Entry10 = tk.Entry(self.Canvas1)
        self.Entry10.place(relx=0.437, rely=0.84,height=26, relwidth=0.427)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(insertbackground="black")

        self.Label11 = tk.Label(self.Canvas1)
        self.Label11.place(relx=0.087, rely=0.84, height=31, width=97)
        self.Label11.configure(anchor='w')
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text='''maxtrainlen''')

        self.Label12 = tk.Label(self.Canvas1)
        self.Label12.place(relx=0.385, rely=0.321, height=30, width=122)
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(font=font10)
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(text='''Rough Tune''')

        self.Label13 = tk.Label(self.Canvas1)
        self.Label13.place(relx=0.402, rely=0.504, height=30, width=100)
        self.Label13.configure(background="#d9d9d9")
        self.Label13.configure(cursor="fleur")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(font=font10)
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(text='''Fine Tune''')

        self.TButton1 = ttk.Button(self.Canvas1)
        self.TButton1.place(relx=0.385, rely=0.916, height=35, width=120)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Start Training''')

if __name__ == '__main__':
    vp_start_gui()





