#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 22, 2020 03:49:14 AM PST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 572x655+664+118
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1050
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    canvas $top.can58 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 75 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can58" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can58
    label $site_3_0.lab59 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Training Hyperparameters} 
    vTcl:DefineAlias "$site_3_0.lab59" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text n_job 
    vTcl:DefineAlias "$site_3_0.lab61" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab62 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text shared_memory 
    vTcl:DefineAlias "$site_3_0.lab62" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text train_rough_len 
    vTcl:DefineAlias "$site_3_0.lab63" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab64 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text train_rough_radiusin 
    vTcl:DefineAlias "$site_3_0.lab64" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text train_rough_radiusfin 
    vTcl:DefineAlias "$site_3_0.lab65" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text train_finetune_len 
    vTcl:DefineAlias "$site_3_0.lab66" "Label7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent68 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent68" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent69 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent69" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent70 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent70" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent71 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent71" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent72 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent72" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent73 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent73" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text train_finetune_radiusin 
    vTcl:DefineAlias "$site_3_0.lab74" "Label8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent75 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent75" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab76 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text train_finetune_radiusfin 
    vTcl:DefineAlias "$site_3_0.lab76" "Label9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent77 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent77" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text train_len_factor 
    vTcl:DefineAlias "$site_3_0.lab78" "Label10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent79 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent79" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent80 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent80" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text maxtrainlen 
    vTcl:DefineAlias "$site_3_0.lab81" "Label11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab83 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Rough Tune} 
    vTcl:DefineAlias "$site_3_0.lab83" "Label12" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab84 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Fine Tune} 
    vTcl:DefineAlias "$site_3_0.lab84" "Label13" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu85 \
        -takefocus {} -text {Start Training} 
    vTcl:DefineAlias "$site_3_0.tBu85" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 140 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 50 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 50 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 50 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 50 -y 250 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 50 -y 290 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 50 -y 370 -anchor nw -bordermode ignore 
    place $site_3_0.ent68 \
        -in $site_3_0 -x 250 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 250 -y 130 -width 244 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent70 \
        -in $site_3_0 -x 250 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.ent71 \
        -in $site_3_0 -x 250 -y 250 -anchor nw -bordermode ignore 
    place $site_3_0.ent72 \
        -in $site_3_0 -x 250 -y 290 -anchor nw -bordermode ignore 
    place $site_3_0.ent73 \
        -in $site_3_0 -x 250 -y 370 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 50 -y 410 -anchor nw -bordermode ignore 
    place $site_3_0.ent75 \
        -in $site_3_0 -x 250 -y 410 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 50 -y 460 -anchor nw -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 250 -y 460 -anchor nw -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 50 -y 500 -anchor nw -bordermode ignore 
    place $site_3_0.ent79 \
        -in $site_3_0 -x 250 -y 500 -anchor nw -bordermode ignore 
    place $site_3_0.ent80 \
        -in $site_3_0 -x 250 -y 550 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 50 -y 550 -anchor nw -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 220 -y 210 -anchor nw -bordermode ignore 
    place $site_3_0.lab84 \
        -in $site_3_0 -x 230 -y 330 -anchor nw -bordermode ignore 
    place $site_3_0.tBu85 \
        -in $site_3_0 -x 220 -y 600 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.can58
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can58 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

